[package]
name = "pad-path"
version = "0.1.0"
authors = ["James Hawley <jamesrichardhawley@gmail.com>"]
edition = "2018"
description = "Intuitively modify your `$PATH`"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.7"

[[bin]]
name = "pad"
path = "src/main.rs"
