[package]
name = "pad-path"
version = "0.1.5"
authors = ["James Hawley <developer@jrhawley.ca>"]
edition = "2018"
description = "Intuitively modify your `$PATH`"
license = "MIT"
repository = "https://github.com/jrhawley/pad-path/"
homepage = "https://github.com/jrhawley/pad-path/"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["cli"]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
itertools = "0.9"

[[bin]]
name = "pad"
path = "src/main.rs"
