[tasks.release-all]
dependencies = [
	"release-windows",
	"release-macos",
	"release-linux",
]

[tasks.release]
linux_alias = "release-linux"
windows_alias = "release-windows"
mac_alias = "release-macos"

[tasks.release-windows]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-pc-windows-gnu",
]

[tasks.release-macos]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-apple-darwin",
]

[tasks.release-linux]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-unknown-linux-musl",
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

