[tasks.push-release]
dependencies = [
	"zip-all"
]
command = "gh"
args = [
	"release",
	"upload",
	"v${CARGO_MAKE_CRATE_VERSION}",
	"target/x86_64-pc-windows-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-pc-windows-gnu.zip",
	"target/x86_64-unknown-linux-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-unknown-linux-gnu.zip",
	# "target/x86_64-apple-darwin/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-apple-darwin.zip",
]

[tasks.zip-all]
dependencies = [
	"zip-windows",
	# "zip-macos",
	"zip-linux",
]

[tasks.zip]
linux_alias = "zip-linux"
windows_alias = "zip-windows"
mac_alias = "zip-macos"

[tasks.zip-windows]
dependencies = [
	"release-windows",
	"clean-zip-windows",
]
command = "7z"
args = [
	"a",
	"target/x86_64-pc-windows-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-pc-windows-gnu.zip",
	"target/x86_64-pc-windows-gnu/release/pad.exe",
]


[tasks.zip-macos]
dependencies = [
	"release-macos",
	"clean-zip-macos",
]
command = "7z"
args = [
	"a",
	"target/x86_64-apple-darwin/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-apple-darwin.zip",
	"target/x86_64-apple-darwin/release/pad",
]

[tasks.zip-linux]
dependencies = [
	"release-linux",
	"clean-zip-linux",
]
command = "7z"
args = [
	"a",
	"target/x86_64-unknown-linux-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-unknown-linux-gnu.zip",
	"target/x86_64-unknown-linux-gnu/release/pad",
]


[tasks.release-all]
dependencies = [
	"release-windows",
	"release-macos",
	"release-linux",
]

[tasks.release]
linux_alias = "release-linux"
windows_alias = "release-windows"
mac_alias = "release-macos"

[tasks.release-windows]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-pc-windows-gnu",
]

[tasks.release-macos]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-apple-darwin",
]

[tasks.release-linux]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-unknown-linux-gnu",
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clean-zip-windows]
condition = {files_exist = ["target/x86_64-pc-windows-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-pc-windows-gnu.zip"]}
command = "rm"
args = [
	"-f",
	"target/x86_64-pc-windows-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-pc-windows-gnu.zip",
]

[tasks.clean-zip-macos]
condition = {files_exist = ["target/x86_64-apple-darwin/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-apple-darwin.zip"] }
command = "rm"
args = [
	"-f",
	"target/x86_64-apple-darwin/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-apple-darwin.zip",
]

[tasks.clean-zip-linux]
condition = {files_exist = ["target/x86_64-unknown-linux-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-unknown-linux-gnu.zip"] }
command = "rm"
args = [
	"-f",
	"target/x86_64-unknown-linux-gnu/release/pad_v${CARGO_MAKE_CRATE_VERSION}_x86_64-unknown-linux-gnu.zip",
]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = [
	"nextest",
	"run",
]

