[tasks.publish]
dependencies = [
	"zip-all"
]
command = "gh"
args = [
	"release",
	"upload",
	"v{version}",
	"target/x86_64-pc-windows-gnu/release/pad_v{version}_x86_64-pc-windows-gnu.zip",
	"target/x86_64-unknown-linux-musl/release/pad_v{version}_x86_64-unknown-linux-musl.zip",
	"target/x86_64-apple-darwin/release/pad_v{version}_x86_64-apple-darwin.zip",
]

[tasks.zip-all]
dependencies = [
	"zip-windows",
	"zip-macos",
	"zip-linux",
]

[tasks.zip]
linux_alias = "zip-linux"
windows_alias = "zip-windows"
mac_alias = "zip-macos"

[tasks.release-all]
dependencies = [
	"release-windows",
	"release-macos",
	"release-linux",
]

[tasks.release]
linux_alias = "release-linux"
windows_alias = "release-windows"
mac_alias = "release-macos"

[tasks.release-windows]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-pc-windows-gnu",
]

[tasks.release-macos]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-apple-darwin",
]

[tasks.release-linux]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release",
	"--target",
	"x86_64-unknown-linux-musl",
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
dependencies = ["clean"]
command = "cargo"
args = ["build"]

[tasks.test]
dependencies = ["clean"]
command = "cargo"
args = ["test"]

